#!/bin/zsh
DICTIONARY=~/Affin.ko/.affin.ko.dictionary

echo "→ ko.lproj 폴더를 생성합니다."

test -d /Applications/Affinity.app/Contents/Resources/ko.lproj
if [[ $? -eq 1 ]]; then
  mkdir /Applications/Affinity.app/Contents/Resources/ko.lproj
fi

test -d /Applications/Affinity.app/Contents/Frameworks/libcocoaui.framework/Versions/A/Resources/ko.lproj
if [[ $? -eq 1 ]]; then
  mkdir /Applications/Affinity.app/Contents/Frameworks/libcocoaui.framework/Versions/A/Resources/ko.lproj
fi

echo "→ Check Update"
cd ~/Affin.ko/
git pull

ENGPATH=/Applications/Affinity.app/Contents/Resources/en-US.lproj/
KORPATH=/Applications/Affinity.app/Contents/Resources/ko.lproj/
FILECOUNT=$(ls -a "${ENGPATH}" | grep "strings" | sed -n "=" | tail -n "1")
for ((i = 1; i <= ${FILECOUNT}; i++)); do
  FILENAME=$(ls "${ENGPATH}" | /usr/bin/sed -n "${i}p")
  printf "→ ${i}/${FILECOUNT}\t${FILENAME}\n"
  iconv -f UTF-16LE -t UTF-8 "${ENGPATH}${FILENAME}" >"${KORPATH}${FILENAME}.temp"
  sed -f "${DICTIONARY}" "${KORPATH}${FILENAME}.temp" >"${KORPATH}${FILENAME}"
done

ENGFPATH=/Applications/Affinity.app/Contents/Frameworks/libcocoaui.framework/Versions/A/Resources/en-US.lproj/
KORFPATH=/Applications/Affinity.app/Contents/Frameworks/libcocoaui.framework/Versions/A/Resources/ko.lproj/
FILECOUNT=$(ls -a "${ENGFPATH}" | grep "strings" | sed -n "=" | tail -n "1")
for ((i = 1; i <= ${FILECOUNT}; i++)); do
  FILENAME=$(ls "${ENGFPATH}" | /usr/bin/sed -n "${i}p")
  printf "→ ${i}/${FILECOUNT}\t${FILENAME}\n"
  iconv -f UTF-16LE -t UTF-8 "${ENGFPATH}${FILENAME}" >"${KORFPATH}${FILENAME}.temp"
  sed -f "${DICTIONARY}" "${KORFPATH}${FILENAME}.temp" >"${KORFPATH}${FILENAME}"
done

open -a Affinity.app
