#!/bin/sh
APPVERS="1.9.0"
APPPATH=/Applications/Affinity\ Designer.app/Contents/Frameworks/libcocoaui.framework/Versions/A/Resources
ENGPATH=${APPPATH}/en.lproj
JAPPATH=${APPPATH}/ja.lproj
KORPATH=${APPPATH}/ko.lproj
MIDPATH=~/Affin.ko-translated/Affinity\ Designer\ \ Frameworks
# array 생성
nib=("AnchorsPage" "AstroStackFilesPage" "AstroStackResultsPage" "DataMergeManagerWindowController" "HyperlinkPage" "IndexPage" "LayerPage" "PackageDocumentWindowController" "ParagraphPage" "Preferences" "ResourceManagerWindowController" "SectionsWindowController" "SnapshotsPage" "TextFramePage" "TocPage" "UserStatusView" "WorkspacePresetWindowController")
# 변환
for (( i = 1; i < ${#nib[@]}; i++ )); do
  echo "Converting ${nib[i]}"
  ENGFILE=${ENGPATH}/${nib[i]}.nib
  JAPFILE=${JAPPATH}/${nib[i]}.nib
  KORFILE=${KORPATH}/${nib[i]}.nib
  MIDFILE=${MIDPATH}/${nib[i]}.nib
  /usr/bin/sudo /usr/bin/plutil -convert xml1 "${ENGFILE}/keyedobjects.nib"
  /usr/bin/sudo /usr/bin/plutil -convert xml1 "${JAPFILE}/keyedobjects.nib"
  /usr/bin/sudo /bin/rm -dr "${MIDFILE}"
  /usr/bin/sudo /bin/mkdir "${MIDFILE}"
  sudo chmod 777 "${MIDFILE}"
  sudo sed -f ~/Affin.ko/DictionaryDesigner "${ENGFILE}/keyedobjects.nib" > "${MIDFILE}/keyedobjects.nib"
  echo -n " (en에서 mid-kr로)"
  /usr/bin/sudo /usr/bin/diff "${ENGFILE}" "${JAPFILE}" | /usr/bin/grep "<string>" > ~/Affin.ko/Diff/Affinity\ Designer/Frameworks/${nib[i]}.nib.en-ja.log
  /usr/bin/sudo /usr/bin/diff "${ENGFILE}" "${MIDFILE}" | /usr/bin/grep "<string>" > ~/Affin.ko/Diff/Affinity\ Designer/Frameworks/${nib[i]}.nib.en-ko.log
  /usr/bin/sudo /usr/bin/diff ~/Affin.ko/Diff/Affinity\ Designer/Frameworks/${nib[i]}.nib.en-ja.log ~/Affin.ko/Diff/Affinity\ Designer/Frameworks/${nib[i]}.nib.en-ko.log | /usr/bin/grep "<string>" > ~/Affin.ko/Diff/Affinity\ Designer/Frameworks/${nib[i]}.nib.ja-ko.log
  echo " (log 파일 생성)"
  git add ~/Affin.ko/Diff/
  git commit -m "Affinity Designer ${APPVERS} ${nib[i]}.nib/ Updated"
done
sudo rm -dr "${MIDPATH}/.DS_Store"
sudo rm -dr "${MIDPATH}/Preferences.nib"
sudo rsync -av --delete "${MIDPATH}" "${KORPATH}"
echo " (mid-kr에서 kr로)"
