#!/bin/bash
sudo echo "새로운 번역을 확인합니다."
cd ~/Affinity-in-Korean/
/usr/bin/git pull
echo "Affinity Publisher Beta을(를) 번역합니다. (총 15개 항목) ^+C로 취소가 가능합니다."
DICPATH=~/Affinity-in-Korean/DictionaryPublisher
ENGPATH=/Applications/Affinity\ Publisher\ Beta.app/Contents/Resources/en.lproj/
KORPATH=/Applications/Affinity\ Publisher\ Beta.app/Contents/Resources/ko.lproj/
for (( i = 1; i <= 15; i++ ))
do
  NAME=$(/bin/ls -a "${ENGPATH}" | /usr/bin/grep "i" | /usr/bin/sed -n "$i"p | /usr/bin/sed -e "s/^.*\///")
  echo -n "${i} ${NAME}"
  /usr/bin/sudo /usr/bin/sed -f "${DICPATH}" "${ENGPATH}${NAME}" > "${KORPATH}${NAME}"
  echo " (번역 완료)"
done

echo "Affinity Publisher Beta (Frameworks)을(를) 번역합니다. (총 304개 항목) ^+C로 취소가 가능합니다."
ENGPATH=/Applications/Affinity\ Publisher\ Beta.app/Contents/Frameworks/libcocoaui.framework/Versions/A/Resources/en.lproj/
KORPATH=/Applications/Affinity\ Publisher\ Beta.app/Contents/Frameworks/libcocoaui.framework/Versions/A/Resources/ko.lproj/
for (( i = 1; i <= 304; i++ ))
do
  NAME=$(/bin/ls -a "${ENGPATH}" | /usr/bin/grep "i" | /usr/bin/sed -n "$i"p | /usr/bin/sed -e "s/^.*\///")
  echo -n "${i} ${NAME}"
  /usr/bin/sudo /usr/bin/sed -f "${DICPATH}" "${ENGPATH}${NAME}" > "${KORPATH}${NAME}"
  echo " (번역 완료)"
done
