#!/bin/bash
PROGRAM=Designer/
GITPATH=~/Affinity-in-Korean/
DICPATH=~/Affinity-in-Korean/DictionaryDesigner
ENGPATH=/Applications/Affinity\ Designer.app/Contents/Resources/en.lproj/
JAPPATH=/Applications/Affinity\ Designer.app/Contents/Resources/ja.lproj/
KORPATH=/Applications/Affinity\ Designer.app/Contents/Resources/ko.lproj/
echo "Affinity Designer을(를) 번역합니다. (총 12개 항목) ^+C로 취소가 가능합니다."
for (( i = 1; i <= 12; i++ ))
do
  NAME=$(/bin/ls -a "${ENGPATH}" | /usr/bin/grep "i" | /usr/bin/sed -n "${i}"p | /usr/bin/sed -e "s/^.*\///")
  echo -n "${i} ${NAME}"
  sed -f "${DICPATH}" "${ENGPATH}${NAME}" > "${KORPATH}${NAME}"
  echo -n " (번역 종료)"
  diff "${ENGPATH}${NAME}" "${JAPPATH}${NAME}" | grep -E "<string>|.nib|.strings" > "${GITPATH}${PROGRAM}${NAME}".en-ja.log
  diff "${ENGPATH}${NAME}" "${KORPATH}${NAME}" | grep -E "<string>|.nib|.strings" > "${GITPATH}${PROGRAM}${NAME}".en-ko.log
  echo " (기록 종료)"
  cd "${GITPATH}"
  git add "${PROGRAM}"
  git commit -m "${PROGRAM}${NAME}.log 변경"
  git push
  echo " (git 종료)"
done
