#!/bin/bash
PROGRAM=Publisher\ Beta/Frameworks/
GITPATH=~/Affinity-in-Korean/
DICPATH=~/Affinity-in-Korean/DictionaryPublisher
ENGPATH=/Applications/Affinity\ Publisher\ Beta.app/Contents/Frameworks/libcocoaui.framework/Versions/A/Resources/en.lproj/
JAPPATH=/Applications/Affinity\ Publisher\ Beta.app/Contents/Frameworks/libcocoaui.framework/Versions/A/Resources/ja.lproj/
KORPATH=/Applications/Affinity\ Publisher\ Beta.app/Contents/Frameworks/libcocoaui.framework/Versions/A/Resources/ko.lproj/
echo "Affinity Publisher Beta (Frameworks)을(를) 번역합니다. (총 304개 항목) ^+C로 취소가 가능합니다."
for (( i = 1; i <= 304; i++ ))
do
  NAME=$(/bin/ls -a "${ENGPATH}" | /usr/bin/grep "i" | /usr/bin/sed -n "${i}"p | /usr/bin/sed -e "s/^.*\///")
  echo -n "${i} ${NAME}"
  sed -f "${DICPATH}" "${ENGPATH}${NAME}" > "${KORPATH}${NAME}"
  echo -n " (번역 종료)"
  diff "${ENGPATH}${NAME}" "${JAPPATH}${NAME}" | grep -E "<string>|.nib|.strings" > "${GITPATH}${PROGRAM}${NAME}".en-ja.log
  diff "${ENGPATH}${NAME}" "${KORPATH}${NAME}" | grep -E "<string>|.nib|.strings" > "${GITPATH}${PROGRAM}${NAME}".en-ko.log
  echo " (기록 종료)"
  cd "${GITPATH}"
  git add "${PROGRAM}"
  git commit -m "${PROGRAM}${NAME}.log 변경"
  git push
  echo " (git 종료)"
done
